### ISSUE TITLE
ERROR 404 PRE BUILT INDEXES ERROR...

### ISSUE THREAD

**Issue by cmorris2945** [bioturing/hera-t#20]
Hello. 

I’m trying to install and run your
Hera –T gene analysis software application,
but I keep getting error 404 from the “drop box”
for the gene index.

Do you know about this?
Do you have an alternative website
or package I can go to?

Thank you,

**Comment by ptdtan** [comment]
Please try again. I just updated the links.

Thank you.

**Comment by cmorris2945** [comment]
There is another issue now.There is some sort of segmentation fault error.Please look into this.
"When one has not had a good father, one must create one..."  
- Friedrich Nietzsche 
Philosopher, poet1844-1900 

    On Sunday, April 19, 2020, 04:11:17 AM EDT, Phan Thai Duy Tan <notifications@github.com> wrote:  
 
 


Please try again. I just updated the links.

Thank you.
